name: library_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.5.3
  firebase_core: ^3.13.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/google icon.png
    - assets/images/logo.jpg
    - assets/images/person.jpg
    - assets/images/Reset password-rafiki.png
    - assets/booksImages/

  fonts:
    - family: Lucida Calligraphy
      fonts:
        - asset: assets/fonts/Lucida Calligraphy Bold.otf
