// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAg3wz5FVUalyVpT-GhUbsUtgDBhnan0Zw',
    appId: '1:87424500452:web:7063e91fd2d0e9b66e62f1',
    messagingSenderId: '87424500452',
    projectId: 'library-app-76932',
    authDomain: 'library-app-76932.firebaseapp.com',
    storageBucket: 'library-app-76932.firebasestorage.app',
    measurementId: 'G-3L2N2TSF3H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9A-HT755oURLtJkIh-LvlP_MUwK6oKp4',
    appId: '1:87424500452:android:13d3a54e196d96746e62f1',
    messagingSenderId: '87424500452',
    projectId: 'library-app-76932',
    storageBucket: 'library-app-76932.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgUgmgoMO82AO5vzGIPcbqv7ktwKg8J9E',
    appId: '1:87424500452:ios:08d966737415e7436e62f1',
    messagingSenderId: '87424500452',
    projectId: 'library-app-76932',
    storageBucket: 'library-app-76932.firebasestorage.app',
    iosBundleId: 'com.example.libraryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgUgmgoMO82AO5vzGIPcbqv7ktwKg8J9E',
    appId: '1:87424500452:ios:08d966737415e7436e62f1',
    messagingSenderId: '87424500452',
    projectId: 'library-app-76932',
    storageBucket: 'library-app-76932.firebasestorage.app',
    iosBundleId: 'com.example.libraryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAg3wz5FVUalyVpT-GhUbsUtgDBhnan0Zw',
    appId: '1:87424500452:web:f912609f32b347cb6e62f1',
    messagingSenderId: '87424500452',
    projectId: 'library-app-76932',
    authDomain: 'library-app-76932.firebaseapp.com',
    storageBucket: 'library-app-76932.firebasestorage.app',
    measurementId: 'G-QNT193GWMR',
  );
}
